### ISSUE TITLE
[Feature] Publish ESM modules

### ISSUE THREAD

**Issue by IanVS** [storybookjs/addon-kit#10]
### Describe the Feature

It is important for modern build tools (like the storybook vite builder) to expose an ESM build.  The official addon-kit should enable this by default, to ensure that the ecosystem of storybook plugins uses this best-practice.

It sounds like varun from discord is working on this currently, but I thought it might be good to have an issue to track it.

**Comment by winkerVSbecks** [comment]
I am Varun from discord 👋🏽 
Thanks for creating the issue. I was getting the ESM stuff working in measure first then going to backport it to the kit.
