### ISSUE TITLE
[documentation][question] Best practices for passing configuration (e.g. API keys) into an addon 

### ISSUE THREAD

**Issue by hydrosquall** [storybookjs/addon-kit#16]
Thanks for making this template! I am trying it out with https://github.com/hydrosquall/storybook-addon-datadog-rum

I was wondering whether there's a recommended path for passing in configuration parameters into an addon.

I looked at the `google-analytics` plugin as an example, and noticed it is configured using assignments to the global window in `preview.js`

https://github.com/storybookjs/storybook/tree/a33ec342b56009ad17bfa9a64a0cb45e8eda96cf/addons/google-analytics

This works, but it seems risky (e.g. naming collisions, other programs could overwrite this, and associated dangers of putting things on the global namespace).

Is there a recommended way / example plugin which would let me pass in "addon configuration" as a parameter that would show up in the registration callback instead? Ideally I would like to pass these into `storybook/.main.js`, similar to how babel plugins are configurable (e.g. you can pass just the name, or a 2-item array containing the name in the first slot, and the options in the second slot). Wasn't sure if this is already possible, or a feature request to file for the core storybook repo.

https://github.com/storybookjs/storybook/blob/a33ec342b56009ad17bfa9a64a0cb45e8eda96cf/addons/google-analytics/src/register.ts#L7

**Comment by winkerVSbecks** [comment]
@hydrosquall I would say global params are probably the best option https://storybook.js.org/docs/react/addons/configure-addons#parameters

TBH I'm not sure why the GA addon uses window references. Might be a legacy thing.

**Comment by hydrosquall** [comment]
@winkerVSbecks , thanks for taking a look!  

> Users can provide global defaults and then override them at the story level.

I'm interested in providing these defaults at the level of `storybook/main.js` or `storybook/preview.js` since I don't plan to use these variables inside my stories (this is meant to be used by instrumentation in the page wrapper). Do you know of any example other plugins besides the example https://storybook.js.org/addons/storybook-addon-pseudo-states that need to be configured like this? 

The pseudo-state addon is helpful to know about, but I'm not sure it would work for an instrumentation situation like what both google analytics and a RUM solution would need.

**Comment by winkerVSbecks** [comment]
Two options:

1. You can specify a default for globals or params in `preset/preview` file. eg: https://github.com/storybookjs/addon-measure/blob/main/src/preset/preview.js#L15 A lot of addons eg: viewport, actions, controls, etc. use this pattern

2.  Checkout the essentials addon: https://github.com/storybookjs/storybook/blob/next/addons/essentials/src/index.ts You can also configure the addon by passing in options in `storybook/main.js`, sort of how babel plugins work. This will require you to adjust your `preset.js` file. Controls addon does something similar too https://github.com/storybookjs/storybook/blob/next/addons/controls/preset.js
