### ISSUE TITLE
What does `module.hot.decline` in `index.ts` do?

### ISSUE THREAD

**Issue by kaelig** [storybookjs/addon-kit#41]
I'm really curious about the purpose of this code, can you say more?

https://github.com/storybookjs/addon-kit/blob/4c3224fbbe9d3c663e88d11f563c91ebc10b0b4f/src/index.ts#L1-L3

**Comment by winkerVSbecks** [comment]
I believe it rejects HMR updates for the addon when the story/component code changes. @shilman @ndelangen  could you confirm.

**Comment by ndelangen** [comment]
yes

**Comment by kaelig** [comment]
Thank you both! 🙏🏻
