### ISSUE TITLE
Upgrade to storybook 7

### ISSUE THREAD

**Issue by mathisobadia** [storybookjs/addon-kit#43]
Hello,

I have created a atorybook addon using this addon kit as a starter. I now want to upgrade my addon to make it compatible with storybook 7 beta. Would it be possible to make this starter template compatible with storybook 7 so that I can look at the changes necessary to upgrade my own addon? 

I understand storybook 7 is still in beta but it would be nice if we had a way to upgrade our addons before the official release. maybe a separate branch so that people creating addons now still have something compatible with the current version of storybook.

thanks

**Comment by winkerVSbecks** [comment]
@mathisobadia yes, I'm planning to release that soon. Next week at the latest.

**Comment by mathisobadia** [comment]
@winkerVSbecks  glad to hear this thank you !

**Comment by winkerVSbecks** [comment]
@mathisobadia I've got a beta branch up. Do you want to give it a go? https://github.com/storybookjs/addon-kit/pull/45

**Comment by winkerVSbecks** [comment]
Thanks, that's helpful feedback. I'll make the necessary adjustments.
