### ISSUE TITLE
[Bug] yarn release - not working

### ISSUE THREAD

**Issue by lukastanisic99** [storybookjs/addon-kit#57]
### Describe the bug

First of all I'd like to say that I've made my addon, published it to npm and installed it to a few other projects and it's working. I've done it by building the project and running `npm publish` - prior to that run `npm adduser` if you haven't done that already.

The `yarn release` command is not working. It passes the `yarn build` but fails at `yarn auto shipit`
I have the GitHub and NPM toknes generated with all the required permissions as described in this article - https://storybook.js.org/docs/react/addons/writing-addons#publishing-to-npm

I've also tried publishing the package using the CI automation as described in the article and it doesn't work. 

The error message I get is:
`
Error: Running command 'npm' with args [version, 0.2.1, --no-commit-hooks, -m, 'Bump version to: %s [skip ci]'] failed

npm ERR! code EUSAGE
npm ERR!
npm ERR! Bump a package version
npm ERR!
npm ERR! Usage:
npm ERR! npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]
npm ERR!
npm ERR! Options:
npm ERR! [--allow-same-version] [--no-commit-hooks] [--no-git-tag-version] [--json]
npm ERR! [--preid prerelease-id] [--sign-git-tag]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--no-workspaces-update] [--include-workspace-root]
npm ERR!
npm ERR! alias: verison
npm ERR!
npm ERR! Run "npm help version" for more info
`

There isn't much information out there on the internet and I haven't spent a significant amount of time debugging this, since there are easier way to publish the package as stated above. 
However I did take a look at a couple of issues one of them being https://github.com/intuit/auto/issues/1509
All the commands work on their own both on windows and wsl - so I'm not sure what's the problem. 

Just wanted to let you guys know and if anyone else encounters problems, try publishing directly - that worked for me.

**Comment by winkerVSbecks** [comment]
Auto is there as convenience, you're welcome to use any publishing mechanism. Based on the issue you linked, it's likely an issue with your local setup (most likely npm). 

I'm going to close for now cause since there's no reproduction and a bunch of addons use this setup without any issue.
