### ISSUE TITLE
[Bug]: Deprecated APIs and types are being used

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/addon-kit#65]
### Describe the bug

The APIs used to register the manager-specific parts of the addon is deprecated and using some properties that TypeScript says are wrong. I don't have the full picture of how wrong it actually is, or what the non-deprecated APIs to migrate to would be, but we should probably change it.

This is also [in the documentation](https://storybook.js.org/docs/addons/writing-addons), so what ever we figure out we should remember to update the docs as well.

### Screenshots and/or logs

These are screenshots from just opening `manager.ts` from this repo. https://github.com/storybookjs/addon-kit/blob/main/src/manager.ts

![image](https://github.com/storybookjs/addon-kit/assets/5678122/255e6561-7b6b-4b34-97ba-06ba3e0cba6a)

### deprecated `types` import

![image](https://github.com/storybookjs/addon-kit/assets/5678122/e65e9f75-c3f2-45ad-a3db-864111a7fb40)

### Tool definition

![image](https://github.com/storybookjs/addon-kit/assets/5678122/6af68457-1989-4992-ba3d-8d30f35a863f)

### Panel definition

![image](https://github.com/storybookjs/addon-kit/assets/5678122/7562f960-b0fe-4a51-b97c-556a0d1db0ab)

### Tab definition

![image](https://github.com/storybookjs/addon-kit/assets/5678122/64150253-ef20-43c4-8391-1bfe11f4d791)

**Comment by vanessayuenn** [comment]
@ndelangen will undeprecate this
